### ISSUE TITLE
Where i have to define @dict 

### ISSUE THREAD

**Issue by eliogsolis** [xfra35/f3-multilang#14]
i saw an example
here
https://groups.google.com/forum/#!topic/f3-framework/NAhOB6rL6sw

im trying this 
<body>
      {{ @dict.hello }}
  </body>

but it doesnt work, can you help me please?

**Comment by xfra35** [comment]
Hi,

In order to define a dictionary, you should follow the steps below:
1. create a folder (for example `dict/`) with a dictionary file for each supported language. For example, `en.ini`, `nl.ini` and `zh.ini` for English, Dutch and Chinese. Each dictionary file contains a list of key-value pairs, such as `hello = 你好`.
2. instruct the framework about the dictionary folder location: `$f3->LOCALES='dict/';`
3. instruct the framework about the user language: `$f3->LANGUAGE='zh';`
4. now `echo $f3->hello` outputs `你好`

NB1: when using the `Multilang` plugin, step 3 is automatically handled by the plugin (language is detected from the URI).

NB2: you can automatically prefix all dictionary entries. For example:
- `$f3->PREFIX='DICT.'` will store the previous entry to `$f3->DICT['hello']`
- `$f3->PREFIX='dict_'` will store it to `$f3->dict_hello`

See the framework [documentation](http://fatfreeframework.com/views-and-templates#multilingual-support) for more details.

**Comment by eliogsolis** [comment]
Not working for me 
My index.php

```
require('vendor/autoload.php');
    $f3=Base::instance();
    $f3->config('app/config.ini');
    $f3->config('app/routes.ini');

    Multilang::instance();
    $f3->set('LOCALES','/dict');
    $f3->set('PREFIX','dict_');
    $f3->run();
```

My dict/en 
hello = Hello

and dict/es
hello = Hola
Controllor just doing an echo $f3->dict_hello;

**Comment by xfra35** [comment]
It should be `$f3->set('LOCALES','dict/')`.

**Comment by eliogsolis** [comment]
Well... actually the plugin is working with URL's 
`/multilang/es`
but still not working in my controller (i made the change that you suggested)

```
$f3->get('dict_hello');
$f3->get('dict.hello');
$f3->get('DICT.hello');
$f3->dict_hello;
```

Thanks for the help!!  And sorry for my bad english...

**Comment by xfra35** [comment]
What do you mean by "not working"? Does it output an empty string? or a bad translation?

**Comment by eliogsolis** [comment]
Gettin null from  
`var_dump($f3->get('DICT.hello'));`
or empty if i use an echo
`echo $f3->dict_hello;`

**Comment by xfra35** [comment]
Try to output `$f3->LANGUAGE` just after the plugin instantiation to see if Spanish is detected.

**Comment by eliogsolis** [comment]
Gettin
es-ES,es,en-GB,en,en-US

**Comment by xfra35** [comment]
The detection is correct. So there's an issue with your dictionary files.

You should have:
- `LOCALES=dict/`
- `PREFIX=dict.`

Your folder structure should look like:

```
app/
dict/
  es.ini
vendor/
index.php
```

`es.ini` should look like:

``` ini
hello = Hola
thanks = Gracias
```

After which, `print_r($f3->dict)` should output an array containing `Hola` and `Gracias`.

**Comment by eliogsolis** [comment]
Mmm... (T-T) ...  I dont know why its not working for me... 

![image](https://cloud.githubusercontent.com/assets/19827421/15983434/68cf591c-2f6d-11e6-9483-1ae618cef01b.png)

es.ini 
![image](https://cloud.githubusercontent.com/assets/19827421/15983437/84997272-2f6d-11e6-8af1-8289bd2b2730.png)

my index just in case
![image](https://cloud.githubusercontent.com/assets/19827421/15983442/b67510f8-2f6d-11e6-80ad-2be917aa2114.png)

my controller 
![image](https://cloud.githubusercontent.com/assets/19827421/15983450/f137f4d0-2f6d-11e6-92a6-22fa8da5eb69.png)

And my config.ini  and routes.ini
![image](https://cloud.githubusercontent.com/assets/19827421/15983483/89eaef98-2f6e-11e6-851e-395b07c0bc9e.png)

![image](https://cloud.githubusercontent.com/assets/19827421/15983485/9377c180-2f6e-11e6-98f6-95f2828d1eba.png)

**Comment by ikkez** [comment]
You don't need to have `dict/` in your autoload path. 
And in case, it should be `AUTOLOAD = "app/;dict/"`
otherwise it becomes an array without the " " around it, which could cause misbehaviour for the autoloader, as this is a special edge case for custom autoload functions

**Comment by xfra35** [comment]
@eliogsolis you're defining `PREFIX` _after_ loading the dictionary (via `LOCALES`), so the term is stored in `hello` instead of `dict.hello`.

Just reverse the two lines to fix your problem:

``` php
$f3->PREFIX='dict.';
$f3->LOCALES='dict/';
```

I've just added a mention about it in the [docs](http://fatfreeframework.com/quick-reference#PREFIX).

**Comment by xfra35** [comment]
@ikkez the issue you're describing occurs with commas, not semicolons. This is because `$f3->config` uses `str_getcsv` to split values, not `$f3->split`.

Anyway thanks for mentioning it. It's good to know that semicolons are safer to use in config files. I've just added a warning for it in the [docs](http://fatfreeframework.com/quick-reference#AUTOLOAD).
